# Generated by Django 5.0.2 on 2024-02-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateField(auto_now=True)),
                ('department', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'db_table': 'journal',
            },
        ),
    ]
