# Generated by Django 5.0.2 on 2024-02-21 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('solution', models.TextField(verbose_name='Решение проблемы')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department', verbose_name='Отдел')),
                ('tags', models.ManyToManyField(to='journal.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'db_table': 'journal',
            },
        ),
    ]
