# Generated by Django 5.0.2 on 2024-02-12 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='solution',
            field=models.TextField(verbose_name='Решение проблемы'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.CharField(max_length=100, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
