# Generated by Django 5.0.2 on 2024-02-12 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_create_dt_alter_journal_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'department',
            },
        ),
        migrations.AlterField(
            model_name='journal',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.department', verbose_name='Отдел'),
        ),
    ]
