# Generated by Django 5.0.2 on 2024-02-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_department_alter_journal_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="department",
            field=models.CharField(max_length=255, verbose_name="Отдел"),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
