# Generated by Django 5.0.2 on 2024-02-13 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_alter_journal_department_delete_department"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.department",
                verbose_name="Отдел",
            ),
        ),
    ]
