# Generated by Django 5.0.2 on 2024-02-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_alter_journal_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тега"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "db_table": "tag",
            },
        ),
        migrations.AddField(
            model_name="journal",
            name="update_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.RemoveField(
            model_name="journal",
            name="tags",
        ),
        migrations.AddField(
            model_name="journal",
            name="tags",
            field=models.ManyToManyField(to="journal.tag", verbose_name="Теги"),
        ),
    ]
