# Generated by Django 5.0.2 on 2024-02-21 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвертизационный номер')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('AW', 'Ожидание заправки'), ('RF', 'На заправке'), ('CH', 'На проверке'), ('RD', 'Заправленный'), ('IU', 'В работе')], default='AW', max_length=2, verbose_name='Статус')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('status_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления статуса')),
            ],
            options={
                'verbose_name': 'Картриджи',
                'verbose_name_plural': '1. Картриджи',
                'db_table': 'cartridges',
            },
        ),
        migrations.CreateModel(
            name='PrintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page_count', models.IntegerField(verbose_name='Количество страниц при установке')),
                ('end_page_count', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц перед заправкой')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата установки')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge', verbose_name='Картридж')),
            ],
            options={
                'verbose_name': 'Отпечатки',
                'verbose_name_plural': '3. Отпечатки',
                'db_table': 'print_record',
            },
        ),
        migrations.CreateModel(
            name='RefillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_number', models.CharField(max_length=100, unique=True, verbose_name='Номер заправки')),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки на заправку')),
                ('notice', models.TextField(default='', verbose_name='Примечание')),
                ('cartridges', models.ManyToManyField(to='cartridges.cartridge', verbose_name='Картриджи')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': '2. Заправка',
                'db_table': 'refill_record',
            },
        ),
    ]
