# Generated by Django 5.0.2 on 2024-08-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartridges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillrecord',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
