# Generated by Django 5.0.2 on 2024-02-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartridges", "0002_alter_cartridge_inventory_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartridge",
            options={
                "verbose_name": "1. Картриджи",
                "verbose_name_plural": "1. Картриджи",
            },
        ),
        migrations.AlterModelOptions(
            name="printrecord",
            options={
                "verbose_name": "3. Отпечатки",
                "verbose_name_plural": "3. Отпечатки",
            },
        ),
        migrations.AlterModelOptions(
            name="refillrecord",
            options={
                "verbose_name": "2. Заправка",
                "verbose_name_plural": "2. Заправка",
            },
        ),
        migrations.AddField(
            model_name="refillrecord",
            name="notice",
            field=models.TextField(default="", verbose_name="Примечание"),
        ),
    ]
