# Generated by Django 5.0.2 on 2024-08-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': [models.OrderBy(models.F('directorate'), nulls_last=True)], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отдел'},
        ),
    ]
