# Generated by Django 5.0.2 on 2024-02-20 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип Оборудования',
                'verbose_name_plural': 'Типы Оборудования',
                'db_table': 'type_equipment',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Инвентарынй номер')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('IN_WORK', 'В Работе'), ('IN_REPAIR', 'В Ремонте'), ('BROKEN', 'Сломан'), ('ON_WRITE_OFF', 'На списание'), ('WRITE_OFF', 'Списанно')], default='NEW', max_length=12, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('notes', models.TextField(blank=True, verbose_name='Записи')),
                ('is_component', models.BooleanField(default=False, verbose_name='Является составным')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Отдел / Подразделение')),
                ('parent_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipment', verbose_name='Основное оборудование')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.typeequipment', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('NEW', 'Новый'), ('IN_WORK', 'В Работе'), ('IN_REPAIR', 'В Ремонте'), ('BROKEN', 'Сломан'), ('ON_WRITE_OFF', 'На списание'), ('WRITE_OFF', 'Списанно')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('NEW', 'Новый'), ('IN_WORK', 'В Работе'), ('IN_REPAIR', 'В Ремонте'), ('BROKEN', 'Сломан'), ('ON_WRITE_OFF', 'На списание'), ('WRITE_OFF', 'Списанно')], max_length=20, verbose_name='Новый статус')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'История статусов оборудования',
                'verbose_name_plural': 'Истории статусов оборудования',
                'db_table': 'equipment_status_history',
            },
        ),
    ]
