# Generated by Django 5.0.2 on 2024-07-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'IPAM',
                'verbose_name_plural': '1. IPAM',
                'db_table': 'ipam',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manafacture', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('hostname', models.CharField(max_length=100, verbose_name='Хост')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Свитч',
                'verbose_name_plural': '2. Свитч',
                'db_table': 'switch',
            },
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=100, verbose_name='Порт')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.switch')),
            ],
            options={
                'verbose_name': 'Порты',
                'verbose_name_plural': '3. Порты',
                'db_table': 'ports',
            },
        ),
    ]
