# Generated by Django 5.0.2 on 2024-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_ipam_options_remove_ports_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Хостнейм'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Производитель'),
        ),
    ]
