# Generated by Django 5.0.2 on 2024-02-12 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cartridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        max_length=100, verbose_name="Инвертизационный номер"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NW", "Новый"),
                            ("AW", "Ожидание заправки"),
                            ("RF", "На заправке"),
                            ("CH", "На проверке"),
                            ("RD", "Заправленный"),
                            ("IU", "В работе"),
                        ],
                        default="AW",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "status_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления статуса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Картриджи",
                "verbose_name_plural": "Картриджи",
                "db_table": "cartriges",
            },
        ),
        migrations.CreateModel(
            name="RefillRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refill_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер заправки"
                    ),
                ),
                (
                    "date_sent",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата отправки на заправку",
                    ),
                ),
                (
                    "cartridges",
                    models.ManyToManyField(
                        to="cartringes.cartridge", verbose_name="Картриджи"
                    ),
                ),
            ],
            options={
                "verbose_name": "На Заправке",
                "verbose_name_plural": "На Заправке",
                "db_table": "refill_record",
            },
        ),
    ]
