# Generated by Django 5.0.2 on 2024-02-12 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartringes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refillrecord",
            options={"verbose_name": "Заправка", "verbose_name_plural": "Заправка"},
        ),
        migrations.CreateModel(
            name="PrintRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_page_count",
                    models.IntegerField(
                        verbose_name="Количество страниц при установке"
                    ),
                ),
                (
                    "end_page_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество страниц перед заправкой",
                    ),
                ),
                (
                    "date_recorded",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата установки"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "cartridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cartringes.cartridge",
                        verbose_name="Картридж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счетчики картриджа",
                "verbose_name_plural": "Счетчики картриджа",
                "db_table": "print_record",
            },
        ),
    ]
