# Generated by Django 5.0.2 on 2024-02-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phonebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cabinet", models.CharField(max_length=255)),
                (
                    "bilding",
                    models.CharField(
                        choices=[
                            ("RK", "Редакторский Корпус"),
                            ("TD", "Теледом"),
                            ("PV", "Павилион"),
                            ("PTVS", "ПТВС"),
                            ("GAR", "Гараж"),
                        ],
                        default="RK",
                        max_length=4,
                        verbose_name="Корпус",
                    ),
                ),
                ("sip", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефонная книга",
                "verbose_name_plural": "Телефонная книга",
                "db_table": "phonebook",
            },
        ),
    ]
