# Generated by Django 5.0.2 on 2024-02-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ФИО')),
                ('cabinet', models.CharField(max_length=255, verbose_name='Кабинет')),
                ('bilding', models.CharField(choices=[('RK', 'Редакторский Корпус'), ('TD', 'Теледом'), ('PV', 'Павилион'), ('PTVS', 'ПТВС'), ('GAR', 'Гараж')], default='RK', max_length=4, verbose_name='Корпус')),
                ('sip', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIP телефон')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Городский телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Телефонная книга',
                'verbose_name_plural': 'Телефонная книга',
                'db_table': 'phonebook',
            },
        ),
    ]
