# Generated by Django 5.0.2 on 2024-08-05 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department', verbose_name='Отдел'),
        ),
    ]
