# Generated by Django 5.0.2 on 2024-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="cabinet",
            field=models.CharField(max_length=255, verbose_name="Кабинет"),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="ФИО"
            ),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Городский телефон"
            ),
        ),
        migrations.AlterField(
            model_name="phonebook",
            name="sip",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SIP телефон"
            ),
        ),
    ]
