# Generated by Django 5.0.2 on 2024-08-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phonebook_job_title_alter_phonebook_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='job_title',
        ),
    ]
