# Generated by Django 5.0.2 on 2024-08-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_remove_phonebook_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='job_title',
            field=models.CharField(default='Введите Должность', max_length=255, verbose_name='Должность'),
        ),
    ]
