# Generated by Django 5.0.2 on 2024-08-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_alter_phonebook_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='bilding',
            field=models.CharField(choices=[('RK', 'Редакторский Корпус'), ('TD', 'Теледом'), ('PV', 'Павильон'), ('PTVS', 'ПТВС'), ('GAR', 'Гараж')], default='RK', max_length=4, verbose_name='Корпус'),
        ),
    ]
